config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :user_groups, except: [:destroy] do
      resources :group_orders, except: [:destroy]
    end
    root 'dashboard#show'
  end

  resources :products, only: [:index, :show] do
    collection do
      get 'category/:category_id', to: 'products#index', as: :category
    end
  end

  resource :cart, only: [:show] do
    resources :cart_items, only: [:create, :destroy], as: 'items', path: 'items' do
      member do
        patch :increment
        patch :decrement
      end
    end
    member do
      post :submit
    end
  end

  resources :orders, only: [:show]

  root 'products#index'
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  has_many :users
  has_many :group_orders
  belongs_to :active_group_order, class_name: 'GroupOrder'

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/user_groups_controller.rb
class Admin::UserGroupsController < Admin::ApplicationController
  def index
    @user_groups = policy_scope(UserGroup)
  end

  def show
    @user_group = UserGroup.find(params[:id])
    authorize(@user_group)
  end

  def new
    @user_group = UserGroup.new
    authorize(@user_group)
  end

  def create
    @user_group = UserGroup.new(user_group_params)
    authorize(@user_group)
    if @user_group.save
      redirect_to admin_user_groups_url, notice: 'User group created successfully'
    else
      render :new
    end
  end

  def edit
    @user_group = UserGroup.find(params[:id])
    authorize(@user_group)
  end

  def update
    @user_group = UserGroup.find(params[:id])
    authorize(@user_group)
    if @user_group.update_attributes(user_group_params)
      redirect_to admin_user_groups_url, notice: 'User group updated successfully'
    else
      render :edit
    end
  end

  private

  def user_group_params
    params.require(:user_group).permit(:name, :address_1, :address_2, :city, :state, :zip)
  end
end

app/views/admin/user_groups/_form.html.slim
= simple_form_for [:admin, @user_group] do |f|
  = f.input :name
  = f.input :address_1
  = f.input :address_2
  = f.input :city
  = f.input :state
  = f.input :zip
  = f.submit

app/views/admin/user_groups/edit.html.slim
h2.container__title Edit User Group
= render 'form'

app/views/admin/user_groups/index.html.slim
h2.container__title User Groups

= button_to 'New User Group', new_admin_user_group_path, method: :get
table
  thead
    th Name
    th Members
    th Actions
  tbody
  - @user_groups.each do |group|
    tr data-user-group-id="#{group.id}"
      td= link_to group.name, admin_user_group_path(group)
      td= group.users.count
      td
      
        = link_to 'Edit', edit_admin_user_group_path(group)
        = ' | '
        = link_to 'New Group Order', new_admin_user_group_group_order_path(group)
    

app/views/admin/user_groups/new.html.slim
h2.container__title New User Group
= render 'form'

app/views/admin/user_groups/show.html.slim
h2.container__title= @user_group.name

h2 Orders
table#group_orders
  thead
    th ID
    th Deadline
    th Scheduled Delivery
  tbody
    - @user_group.group_orders.each do |order|
      tr data-group-order-id="#{order.id}"
        td= link_to(order.id, admin_user_group_group_order_path(@user_group, order))
        td= order.deadline
        td= order.scheduled_delivery