config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :user_groups, except: [:destroy] do
      resources :group_orders, except: [:destroy]
    end
    root 'dashboard#show'
  end

  resources :products, only: [:index, :show] do
    collection do
      get 'category/:category_id', to: 'products#index', as: :category
    end
  end

  resource :cart, only: [:show] do
    resources :cart_items, only: [:create, :destroy], as: 'items', path: 'items' do
      member do
        patch :increment
        patch :decrement
      end
    end
    member do
      post :submit
    end
  end

  resources :orders, only: [:show]

  root 'products#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :items, -> { order(:id) }, class_name: 'CartItem', dependent: :destroy

  def add(product)
    item = find_item_for(product)

    if item
      item.increment(:quantity)
    else
      item = items.build(product: product, quantity: 1)
    end

    item.save!
  end

  def contains?(product)
    find_item_for(product).present?
  end

  def subtotal
    items.inject(0.to_money) { |total, item| total += item.total }
  end

  def shipping
    0.to_money
  end

  def tax
    0.to_money
  end

  def total
    subtotal + shipping + tax
  end

  private

  def find_item_for(product)
    items.detect { |item| item.product_id == product.id }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    authorize(cart)
    @cart = cart
  end

  def submit
    authorize(cart)

    if current_group_order.nil?
      redirect_to cart_url, alert: 'No active group order!' and return
    end

    order = OrderProcessor.convert_cart_to_order!(cart, current_group_order)
    redirect_to order_url(order), notice: 'Your order has been successfully received. Thank you!'
  end

  private

  def current_group_order
    current_user.try(:user_group).try(:active_group_order)
  end
end

app/views/carts/show.html.slim
- if @cart.items.empty?
  center
    p You have no items in your cart.
- else
  .shopping-info
    h2.shopping-info__heading Message Title
    p Lorem ipsum quam sagittis vivamus eleifend netus convallis habitant, velit inceptos aenean netus suspendisse proin molestie vehicula, hac a risus feugiat tellus eleifend consequat. Eleifend eros aenean nec duis mollis ligula lectus ac, etiam ligula sollicitudin sem est luctus habitasse mattis, vestibulum feugiat ultricies quam tempus senectus auctor. Imperdiet sagittis ipsum duis commodo duis mauris viverra sem, elit integer conubia fringilla non aenean nam curae, velit magna risus id aliquam aliquet integer fringilla nunc eleifend dolor luctus a fringilla aliquam vivamus.
  table#cart_items.striped
    thead
      th.description Description
      th.quantity Quantity
      th.order-total Total
    tbody
      - @cart.items.each do |cart_item|
        tr data-product-id="#{cart_item.product_id}"
          td.description= cart_item.description
          td.quantity
            .btn__decrease = button_to '-', decrement_cart_item_path(cart_item), method: :patch
            span.item-quantity = cart_item.quantity 
            .btn__increase = button_to '+', increment_cart_item_path(cart_item), method: :patch
          td.total #{cart_item.total.format} #{link_to 'x', cart_item_path(cart_item), method: :delete}
          
  section#order_summary
    h2 Order Summary
    table
      tbody
        tr.subtotal
          td= "Items (#{@cart.items.count})"
          td= @cart.subtotal.format
        tr.shipping
          td Shipping
          td= @cart.shipping.format
        tr.tax
          td Tax
          td= @cart.tax.format
        tr.total
          td Order Total
          td= @cart.total.format
    center
      = button_to 'Place Order', submit_cart_path, disabled: @cart.items.empty?, class: 'btn__submit'