config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :user_groups, except: [:destroy] do
      resources :group_orders, except: [:destroy]
    end
    root 'dashboard#show'
  end

  resources :products, only: [:index, :show] do
    collection do
      get 'category/:category_id', to: 'products#index', as: :category
    end
  end

  resource :cart, only: [:show] do
    resources :cart_items, only: [:create, :destroy], as: 'items', path: 'items' do
      member do
        patch :increment
        patch :decrement
      end
    end
    member do
      post :submit
    end
  end

  resources :orders, only: [:show]

  root 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  monetize :cost_cents

  def price
    cost #TODO add markup
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    skip_policy_scope
    authorize(:catalog, :show?)
    @presenter = ProductPresenter.new(selected_category_id: params[:category_id])
  end

  def show
  end
end

app/views/products/_cart_summary.html.slim
.cart-summary
  =link_to(cart_total.format, cart_path)

app/views/products/_product.html.slim
div class="#{in_cart?(product) ? 'product product--added' : 'product'}" data-product-id="#{product.id}"
  - if in_cart?(product)
    i.fa.fa-check-square
  .image__container
    center
      a class="fancybox" href="https://s3.amazonaws.com/denverfoods/#{product.part_number}.jpg"
        =image_tag "https://s3.amazonaws.com/denverfoods-thumbnails/#{product.part_number}.jpg", alt: 'Product Image', class: 'product__image'
  h4.product__name= product.name
  hr
  ul.product__details
    li= "Price: <span class='bold-type'>#{product.price}</span>".html_safe
    li= "Unit Price: <span class='bold-type'>1.16 ea.</span>".html_safe
    li= "Date: <span class='bold-type'>#{product.date}</span>".html_safe
    li= "Unit: <span class='bold-type'>#{product.unit}</span>".html_safe
    - if in_cart?(product)
      = button_to 'Add Another', cart_items_path, params: { product_id: product.id }, class: 'button__add-another'
    - else
      = button_to 'Add to Cart', cart_items_path, params: { product_id: product.id }, class: 'button__add-to-cart'

app/views/products/index.html.slim
.categories
  ul
    - @presenter.categories.each do |category|
      li class="#{ 'selected' if category == @presenter.selected_category}"
        = link_to category.name, category_products_path(category)
      - if category.children.any?
        ul
          - category.children.each do |child|
            li class="#{ 'selected' if child == @presenter.selected_category}"
              = link_to child.name, category_products_path(child)
            
section.products
  h2.container__title
    = @presenter.selected_category.try(:name)
  - @presenter.products.each do |product|
    = render 'product', product: product

app/views/products/show.html.slim
/ h1 Products#show