config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :user_groups, except: [:destroy] do
      resources :group_orders, except: [:destroy]
    end
    root 'dashboard#show'
  end

  resources :products, only: [:index, :show] do
    collection do
      get 'category/:category_id', to: 'products#index', as: :category
    end
  end

  resource :cart, only: [:show] do
    resources :cart_items, only: [:create, :destroy], as: 'items', path: 'items' do
      member do
        patch :increment
        patch :decrement
      end
    end
    member do
      post :submit
    end
  end

  resources :orders, only: [:show]

  root 'products#index'
end

app/views/layouts/_flash.html.slim
-if notice 
  div.notice__wrapper
    p = notice

-if alert
  div.notice__wrapper
    p = alert

app/views/layouts/_head.html.slim
title Naturally a Deal
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= csrf_meta_tags
link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet"

app/views/layouts/_header.html.slim
- if policy(:dashboard).show?
  .top-bar
    .top-bar__nav
      i.fa.fa-tachometer
      = link_to 'Admin Dashboard', admin_root_path
header
  .header__wrapper
    h1.site-title 
      = link_to 'Naturally a Deal', root_path
    - if policy(:catalog).show?
      .header__search
        input type="text" placeholder="Search items..."
      nav.header__nav
        = link_to 'Products', root_path
        a href="/" Account
      .header__cart
        .header__cart-total
          a href="#{cart_path}"
            i.fa.fa-shopping-cart
            span 
              = cart_total.format

app/views/layouts/admin.html.slim
doctype html
html
  head
    = render 'layouts/head'
    
  body
    = render 'layouts/header'
    = render 'layouts/flash'
    main
      = render 'admin/shared/menu'
      .content__right
        = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    = render 'layouts/head'
    
  body
    = render 'layouts/header'
    = render 'layouts/flash'
    main
      = yield